#!/bin/bash

#
# Process all the entries in ./input
#

current_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
input_folder=$current_dir/input
backup_folder=$current_dir/backup
output_folder=$current_dir/output

# Ensure input has the correct structure and has at least one file in it
function validateEntryFolder {
	entry_path=$1

	landscape_folder=$entry_path/landscape
	photos_folder=$entry_path/photos
	preview_folder=$entry_path/preview

	if 	[ ! -d $landscape_folder ] 		|| [ ! "$(ls -A $landscape_folder/*)" ] || 
		[ ! -d $photos_folder ] 		|| [ ! "$(ls -A $photos_folder/*)" ] || 
		[ ! -d $preview_folder ] 		|| [ ! "$(ls -A $preview_folder/*)" ]; then

		echo "ERROR: Input folder does not have the correct directory structure, should be:"
		echo
		echo "  input/"
		echo "     my-hike/"
		echo "        landscape/"
		echo "            my-landscape.jpg"
		echo "        preview/"
		echo "            my-preview.jpg"
		echo "        photos/"
		echo "            my-photo1.jpg"
		echo "            my-photo2.jpg"
		echo "            ..."
		exit 1
	fi
}

# Use ImageMagick to convert the image
function magickConvert {
	dimensions=$1
	input_file=$2
	output_file=$3

	convert -resize $dimensions \
	-gravity Center	\
	-strip \
	-quality 95 \
	-interlace plane \
	$input_file $output_file
}

# Use ImageMagick to convert and crop the image
function magickConvertCrop {
	dimensions=$1
	input_file=$2
	output_file=$3

	convert -resize $dimensions^ \
	-gravity Center	\
	-crop $1+0+0 \
	-strip \
	-quality 95 \
	-interlace plane \
	$input_file $output_file
}

# Cleanup
function clean {
	rm -rf $output_folder
	mkdir $output_folder
	cp $input_folder/.gitignore $output_folder
}

# Process an entry folder
function processEntryFolder {
	entry_path=$1
	
	entry_id=`basename $entry_path`
	landscape_folder=$entry_path/landscape
	photos_folder=$entry_path/photos
	preview_folder=$entry_path/preview

	validateEntryFolder $entry_path

	# Create folder for this entry
	entry_output_folder=$output_folder/$entry_id
	mkdir $entry_output_folder

	# Handle landscape
	landscape_file=$landscape_folder/$(ls $landscape_folder | head -1)
	magickConvertCrop 1024x341 $landscape_file $entry_output_folder/$entry_id-landscape.jpg

	# Handle preview
	preview_file=$preview_folder/$(ls $preview_folder | head -1)
	magickConvert 341x $preview_file $entry_output_folder/$entry_id-preview.jpg
	magickConvertCrop 809x422 $preview_file $entry_output_folder/$entry_id-preview-large.jpg

	# Handle photos
	for f in $photos_folder/*.*
	do
		filename=$(basename "$f")
		filename="${filename%.*}"
		magickConvertCrop 341x341 "$f" $entry_output_folder/$entry_id-$filename-thumb.jpg
		magickConvert 1024x1024 "$f" $entry_output_folder/$entry_id-$filename.jpg
	done
}


#
# Main
#

clean

for entry_path in $input_folder/*
do
	if [ -d $entry_path ]; then
		processEntryFolder $entry_path
	fi
done
exit 0
